packages:
  - apps/**
  - packages/**

allowBuilds:
  '@heroui-pro/react': true
  '@nestjs/core': false
  '@sentry/cli': false
  '@swc/core': false
  '@zowe/secrets-for-zowe-sdk': false
  cbor-extract: false
  core-js: false
  esbuild: false
  heroui-native-pro: true
  heroui-pro: true
  sharp: false
  workerd: false

catalog:
  "@cloudflare/workers-types": 4.20260504.1
  "@hono/zod-validator": 0.7.6
  "@neondatabase/serverless": 1.0.2
  "@sentry/cloudflare": 10.32.1
  "@sentry/nextjs": 10.32.1
  "@tailwindcss/postcss": 4.1.18
  "@upstash/redis": 1.35.8
  "@vercel/config": 0.5.1
  '@types/node': 24.12.2
  better-auth: 1.6.8
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.2
  hono: 4.12.19
  tailwindcss: 4.1.18
  typescript: 5.9.3
  zod: 4.2.1

savePrefix: ""
