packages:
  - apps/**
  - packages/**

allowBuilds:
  '@sentry/cli': false
  '@zowe/secrets-for-zowe-sdk': false
  heroui-pro: true
  '@heroui-pro/react': true
  core-js: false
  esbuild: false
  sharp: false
  workerd: false

catalog:
  '@cloudflare/workers-types': 4.20260504.1
  '@hono/zod-validator': 0.7.6
  '@neondatabase/serverless': 1.0.2
  '@sentry/cloudflare': 10.32.1
  '@sentry/nextjs': 10.32.1
  '@tailwindcss/postcss': 4.1.18
  better-auth: 1.6.8
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.2
  hono: 4.12.16
  tailwindcss: 4.1.18
  typescript: 5.9.3
  zod: 4.2.1
